[package]
name = "aoc"
version = "0.1.0"
authors = ["awick"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecount = "^0.6.0"
clap = "^2.33.0"
image = "^0.22.0"